import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex flex-row justify-between p-4 border border-b">
          <div>Company Name</div>
          <nav>
            <ul className="flex flex-row">
              <li className="mx-2">
                <Link href="/">Home</Link>
              </li>
              <li className="mx-2">
                <Link href="/products">Products</Link>
              </li>
              <li className="mx-2">
                <Link href="/blog">Blog</Link>
              </li>
              <li className="mx-2">
                <Link href="/contact">Contact</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
